language: node_js
node_js:
  - '10'
cache: yarn
before_deploy: yarn global add caprover
deploy:
  - provider: script
    script: bash deploy.sh
    skip_cleanup: true
    on:
      master: true
notifications:
  email:
    - ao@variations-of-shadow.com
