language: node_js
node_js:
  - 'node'
cache:
  directories:
    - 'node_modules' # This will tell Travis CI to cache the dependencies
script: npm test
before_deploy: npm install now --no-save # Install Now CLI on Travis
deploy:
  - provider: script
    script:
      now remove --token $NOW_TOKEN fructosedb --safe --yes;
      now --token $NOW_TOKEN;
    skip_cleanup: true
    on:
      master: true
