language: node_js
node_js:
  - '10'
cache: yarn
script: yarn test
before_deploy: npm install now --no-save # Install Now CLI on Travis
deploy:
  - provider: script
    script:
      now remove --token $NOW_TOKEN fructosedb --safe --yes;
      now --token $NOW_TOKEN;
      now alias --token $NOW_TOKEN;
    skip_cleanup: true
    on:
      master: true
notifications:
  email:
    - ao@variations-of-shadow.com
