# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - uses: actions/checkout@v2
    - name: Deploy
      uses: actions/setup-node@v2
      with:
        node-version: 14
        cache: 'yarn'
    - run: yarn
    - run: yarn global add caprover
    - env:
        CAPROVER_MACHINE_01: ${{ secrets.CAPROVER_MACHINE_01 }}
        CAPROVER_MACHINE_02: ${{ secrets.CAPROVER_MACHINE_02 }}
        CAPROVER_PASSWORD: ${{ secrets.CAPROVER_PASSWORD }}
      run: ./deploy.sh
